openapi: 3.0.3
autoinit: true
info:
  title: Ludo Rooms API
  version: 0.1.0
paths:
  /api/rooms/create:
    post:
      summary: Create room
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [stake, mode, maxPlayers]
              properties:
                stake: { type: integer, enum: [10,50,100] }
                mode: { type: string, enum: [Classic, Quick] }
                maxPlayers: { type: integer, enum: [2,4] }
      responses:
        '200':
          description: Room created
  /api/rooms/join:
    post:
      summary: Join room
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [roomId]
              properties:
                roomId: { type: string }
      responses:
        '200':
          description: Room joined
  /api/rooms:
    get:
      summary: List rooms
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: status
          schema: { type: string }
        - in: query
          name: stake
          schema: { type: integer }
        - in: query
          name: mode
          schema: { type: string }
      responses:
        '200':
          description: Rooms list
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
